/**
 * Which item sprites have been generated.
 *
 * Written by tools/artpack.py, not by hand. The interface consults it
 * before drawing so a missing plate falls back to the procedural icon
 * silently, instead of flickering through a failed image load on every
 * redraw — and an inventory redraws constantly.
 */
export const ITEM_PLATES = new Set([
  '_book',
  '_key',
  '_letter',
  '_potion_flat',
  '_potion_round',
  '_potion_tall',
  '_pouch',
  '_scroll',
  'amulet_amulet',
  'amulet_necklace',
  'amulet_pendant',
  'amulet_reliquary',
  'amulet_talisman',
  'arrows',
  'art_alderquiet',
  'art_assessor',
  'art_barrowclean',
  'art_cindrast_yew',
  'art_factors_coat',
  'art_gullwing_mail',
  'art_magpie',
  'art_null_band',
  'art_oakhallow_lance',
  'art_oathkeep',
  'art_ossran_pendant',
  'art_quernstone',
  'art_recant',
  'art_riven_girdle',
  'art_sallowhide',
  'art_sealed_skin',
  'art_second_arrow',
  'art_small_hours',
  'art_standing_ring',
  'art_tharn_staff',
  'art_the_blank',
  'art_thornwick_harness',
  'axe_battle',
  'axe_caldera',
  'axe_executioner',
  'axe_great',
  'axe_hand',
  'axe_war',
  'bellflax',
  'belt_forgeband',
  'belt_girdle',
  'belt_leather',
  'belt_plate',
  'belt_studded',
  'belt_warbelt',
  'blaster_blaster',
  'blaster_rifle',
  'bloodhaw_berries',
  'boots_boots',
  'boots_greaves',
  'boots_leather',
  'boots_marching',
  'boots_plate',
  'boots_sandals',
  'bow_composite',
  'bow_elven',
  'bow_great',
  'bow_long',
  'bow_short',
  'bow_wyrmhorn',
  'chain_chain',
  'chain_elven',
  'chain_ring',
  'chain_scale',
  'chain_splint',
  'chain_sunder',
  'cloak_ashweave',
  'cloak_cape',
  'cloak_cloak',
  'cloak_ermine',
  'cloak_fur',
  'cloak_whalehide',
  'dagger_dagger',
  'dagger_dirk',
  'dagger_emberfang',
  'dagger_kris',
  'dagger_main_gauche',
  'dagger_stiletto',
  'emberfoot_cap',
  'fen_lily',
  'gauntlets_caldera',
  'gauntlets_forge',
  'gauntlets_gauntlets',
  'gauntlets_leather',
  'gauntlets_plate',
  'gauntlets_ring',
  'gem_amethyst',
  'gem_diamond',
  'gem_emerald',
  'gem_opal',
  'gem_pearl',
  'gem_quartz',
  'gem_ruby',
  'gem_sapphire',
  'gem_topaz',
  'helm_coif',
  'helm_crown',
  'helm_great',
  'helm_helm',
  'helm_leather_cap',
  'helm_visored',
  'leather_armour',
  'leather_dragon',
  'leather_elven',
  'leather_hardened',
  'leather_studded',
  'leather_wyrmscale',
  'lockpicks',
  'mace_club',
  'mace_flail',
  'mace_forgehammer',
  'mace_mace',
  'mace_morning_star',
  'mace_war_hammer',
  'philosophers_stone',
  'plate_field',
  'plate_full',
  'plate_gothic',
  'plate_noble',
  'plate_plate',
  'qi_black_harness',
  'qi_choir_key',
  'qi_choir_psalter',
  'qi_choir_roll',
  'qi_crown_of_caerwen',
  'qi_dawnbell_key',
  'qi_dragon_tooth',
  'qi_fletchers_letter',
  'qi_font_ember',
  'qi_glass_lens',
  'qi_greenheart_shard',
  'qi_harbourmasters_seal',
  'qi_hessas_answer',
  'qi_holt_antidote',
  'qi_ledger_manifest',
  'qi_ledger_warrant',
  'qi_longshadow_key',
  'qi_marchwardens_bow',
  'qi_ninefold_seal',
  'qi_order_warrant',
  'qi_phylactery_shell',
  'qi_reliquary',
  'qi_smugglers_ledger',
  'qi_swelling_key',
  'qi_sword_warrant',
  'qi_vessel_pass',
  'qi_white_hart_hide',
  'qi_wysk_cipher',
  'ring_band',
  'ring_loop',
  'ring_oathring',
  'ring_ring',
  'ring_signet',
  'rope',
  'shield_aegis',
  'shield_buckler',
  'shield_bulwark',
  'shield_kite',
  'shield_small',
  'shield_tower',
  'spear_halberd',
  'spear_lance',
  'spear_pike',
  'spear_spear',
  'spear_trident',
  'spear_wyrmpike',
  'spellbook_blank',
  'staff_caldera',
  'staff_elder',
  'staff_long',
  'staff_quarterstaff',
  'staff_rune',
  'staff_staff',
  'sulfur_clump',
  'sunder_alloy',
  'sword_bastard',
  'sword_broad',
  'sword_cutlass',
  'sword_ember',
  'sword_great',
  'sword_long',
  'sword_sabre',
  'tallowroot',
  'torch',
  'vial_of_devil_ichor',
  'vial_of_ooze_distillate',
  'vial_of_troll_blood',
  'wand_blades',
  'wand_charm',
  'wand_death',
  'wand_doom',
  'wand_fire',
  'wand_fireball',
  'wand_harm',
  'wand_ice',
  'wand_ice_blast',
  'wand_incineration',
  'wand_lightning',
  'wand_paralyzing',
  'wand_poison',
  'wand_rock',
  'wand_shrapmetal',
  'wand_sparks',
]);

export const ITEM_PLATE_BASE = 'art/items/';

/**
 * Each plate's width/height after cropping to the paint.
 *
 * Consumers that reserve a box for a sprite need the object's real
 * proportions, not the frame it was generated in — guessing 9:16 for
 * every weapon reserved two and a half times the width a long sword
 * actually needs.
 */
export const ITEM_PLATE_ASPECT = {
  '_book': 0.8041,
  '_key': 0.4179,
  '_letter': 1.1926,
  '_potion_flat': 0.5668,
  '_potion_round': 0.6402,
  '_potion_tall': 0.42,
  '_pouch': 0.7371,
  '_scroll': 1.3063,
  'amulet_amulet': 0.6525,
  'amulet_necklace': 0.7701,
  'amulet_pendant': 0.7443,
  'amulet_reliquary': 0.9079,
  'amulet_talisman': 0.678,
  'arrows': 0.4848,
  'art_alderquiet': 0.9905,
  'art_assessor': 1.1468,
  'art_barrowclean': 4.5856,
  'art_cindrast_yew': 0.2561,
  'art_factors_coat': 0.4768,
  'art_gullwing_mail': 0.5696,
  'art_magpie': 1.1039,
  'art_null_band': 1.2902,
  'art_oakhallow_lance': 3.392,
  'art_oathkeep': 0.8824,
  'art_ossran_pendant': 0.6382,
  'art_quernstone': 0.9639,
  'art_recant': 0.9948,
  'art_riven_girdle': 1.5369,
  'art_sallowhide': 0.6895,
  'art_sealed_skin': 0.3525,
  'art_second_arrow': 3.4674,
  'art_small_hours': 0.4877,
  'art_standing_ring': 1.2579,
  'art_tharn_staff': 0.9918,
  'art_the_blank': 0.6999,
  'art_thornwick_harness': 0.8806,
  'axe_battle': 0.4277,
  'axe_caldera': 0.3102,
  'axe_executioner': 0.3968,
  'axe_great': 0.2847,
  'axe_hand': 0.2669,
  'axe_war': 0.3278,
  'bellflax': 0.8509,
  'belt_forgeband': 2.5924,
  'belt_girdle': 2.4047,
  'belt_leather': 3.5951,
  'belt_plate': 2.8444,
  'belt_studded': 2.172,
  'belt_warbelt': 2.073,
  'blaster_blaster': 0.218,
  'blaster_rifle': 0.2233,
  'bloodhaw_berries': 0.9511,
  'boots_boots': 1.3553,
  'boots_greaves': 0.8576,
  'boots_leather': 1.2203,
  'boots_marching': 1.1315,
  'boots_plate': 0.9534,
  'boots_sandals': 1.4746,
  'bow_composite': 0.2493,
  'bow_elven': 0.2647,
  'bow_great': 0.1555,
  'bow_long': 0.1284,
  'bow_short': 0.1991,
  'bow_wyrmhorn': 0.1926,
  'chain_chain': 0.8406,
  'chain_elven': 0.9313,
  'chain_ring': 0.9,
  'chain_scale': 0.7168,
  'chain_splint': 0.767,
  'chain_sunder': 1.0969,
  'cloak_ashweave': 0.6434,
  'cloak_cape': 0.7682,
  'cloak_cloak': 0.6768,
  'cloak_ermine': 0.7165,
  'cloak_fur': 0.752,
  'cloak_whalehide': 0.8237,
  'dagger_dagger': 0.2504,
  'dagger_dirk': 0.2712,
  'dagger_emberfang': 0.2468,
  'dagger_kris': 0.2267,
  'dagger_main_gauche': 0.3042,
  'dagger_stiletto': 0.2345,
  'emberfoot_cap': 1.1314,
  'fen_lily': 1.2766,
  'gauntlets_caldera': 0.8883,
  'gauntlets_forge': 0.8754,
  'gauntlets_gauntlets': 0.8733,
  'gauntlets_leather': 0.8407,
  'gauntlets_plate': 0.5324,
  'gauntlets_ring': 0.9587,
  'gem_amethyst': 1.1483,
  'gem_diamond': 1.007,
  'gem_emerald': 1.3264,
  'gem_opal': 1.2533,
  'gem_pearl': 1.2348,
  'gem_quartz': 1.1857,
  'gem_ruby': 1.1356,
  'gem_sapphire': 0.9836,
  'gem_topaz': 1.2476,
  'helm_coif': 0.8037,
  'helm_crown': 0.7226,
  'helm_great': 1.0,
  'helm_helm': 0.7458,
  'helm_leather_cap': 0.796,
  'helm_visored': 1.1131,
  'leather_armour': 0.7539,
  'leather_dragon': 0.9284,
  'leather_elven': 0.8607,
  'leather_hardened': 0.7686,
  'leather_studded': 0.7195,
  'leather_wyrmscale': 0.927,
  'lockpicks': 1.2493,
  'mace_club': 0.1775,
  'mace_flail': 0.3014,
  'mace_forgehammer': 0.4575,
  'mace_mace': 0.2939,
  'mace_morning_star': 0.2524,
  'mace_war_hammer': 0.3677,
  'philosophers_stone': 0.9641,
  'plate_field': 0.8868,
  'plate_full': 0.5543,
  'plate_gothic': 0.7366,
  'plate_noble': 0.5357,
  'plate_plate': 0.504,
  'qi_black_harness': 0.8933,
  'qi_choir_key': 0.9879,
  'qi_choir_psalter': 1.0905,
  'qi_choir_roll': 1.2379,
  'qi_crown_of_caerwen': 1.2151,
  'qi_dawnbell_key': 0.7944,
  'qi_dragon_tooth': 0.9534,
  'qi_fletchers_letter': 1.0946,
  'qi_font_ember': 0.9953,
  'qi_glass_lens': 1.0904,
  'qi_greenheart_shard': 0.6529,
  'qi_harbourmasters_seal': 1.0312,
  'qi_hessas_answer': 2.029,
  'qi_holt_antidote': 0.7273,
  'qi_ledger_manifest': 1.1347,
  'qi_ledger_warrant': 1.0585,
  'qi_longshadow_key': 0.3551,
  'qi_marchwardens_bow': 0.8889,
  'qi_ninefold_seal': 1.1136,
  'qi_order_warrant': 1.0077,
  'qi_phylactery_shell': 0.7447,
  'qi_reliquary': 1.3561,
  'qi_smugglers_ledger': 1.3368,
  'qi_swelling_key': 0.9678,
  'qi_sword_warrant': 0.8466,
  'qi_vessel_pass': 0.605,
  'qi_white_hart_hide': 1.2644,
  'qi_wysk_cipher': 0.9979,
  'ring_band': 0.8632,
  'ring_loop': 1.0917,
  'ring_oathring': 0.824,
  'ring_ring': 0.924,
  'ring_signet': 0.8527,
  'rope': 1.1238,
  'shield_aegis': 0.7444,
  'shield_buckler': 1.0,
  'shield_bulwark': 0.7132,
  'shield_kite': 0.7003,
  'shield_small': 1.0,
  'shield_tower': 0.6791,
  'spear_halberd': 0.192,
  'spear_lance': 0.2041,
  'spear_pike': 0.0713,
  'spear_spear': 0.146,
  'spear_trident': 0.2292,
  'spear_wyrmpike': 0.1948,
  'spellbook_blank': 1.332,
  'staff_caldera': 0.1279,
  'staff_elder': 0.1691,
  'staff_long': 0.1337,
  'staff_quarterstaff': 0.0746,
  'staff_rune': 0.0829,
  'staff_staff': 0.1099,
  'sulfur_clump': 1.1086,
  'sunder_alloy': 0.8834,
  'sword_bastard': 0.2807,
  'sword_broad': 0.2275,
  'sword_cutlass': 0.2681,
  'sword_ember': 0.2624,
  'sword_great': 0.2674,
  'sword_long': 0.2432,
  'sword_sabre': 0.2227,
  'tallowroot': 1.0752,
  'torch': 0.74,
  'vial_of_devil_ichor': 0.5983,
  'vial_of_ooze_distillate': 0.5362,
  'vial_of_troll_blood': 0.4883,
  'wand_blades': 0.2101,
  'wand_charm': 0.1069,
  'wand_death': 0.1391,
  'wand_doom': 0.1695,
  'wand_fire': 0.1515,
  'wand_fireball': 0.1402,
  'wand_harm': 0.1688,
  'wand_ice': 0.1622,
  'wand_ice_blast': 0.161,
  'wand_incineration': 0.1147,
  'wand_lightning': 0.1227,
  'wand_paralyzing': 0.1398,
  'wand_poison': 0.2526,
  'wand_rock': 0.1756,
  'wand_shrapmetal': 0.1065,
  'wand_sparks': 0.1761,
};
